Repository SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT, pull requests merged in 2024-05, with the labels that each got.

#37 improved ui adboutus contactus sigin signup
  newsaggregator/build.sh
  newsaggregator/core/__pycache__/__init__.cpython-312.pyc
  newsaggregator/core/__pycache__/admin.cpython-312.pyc
  newsaggregator/core/__pycache__/apps.cpython-312.pyc
  newsaggregator/core/__pycache__/forms.cpython-312.pyc
  newsaggregator/core/__pycache__/models.cpython-312.pyc
  newsaggregator/core/__pycache__/urls.cpython-312.pyc
  newsaggregator/core/__pycache__/views.cpython-312.pyc
  newsaggregator/core/forms.py
  newsaggregator/core/migrations/__pycache__/__init__.cpython-312.pyc
  newsaggregator/core/views.py
  newsaggregator/db.sqlite3
  newsaggregator/news/__pycache__/admin.cpython-312.pyc
  newsaggregator/news/__pycache__/urls.cpython-312.pyc
  newsaggregator/news/__pycache__/views.cpython-312.pyc
  newsaggregator/news/migrations/__pycache__/0001_initial.cpython-312.pyc
  newsaggregator/newsaggregator/__pycache__/settings.cpython-312.pyc
  newsaggregator/newsaggregator/__pycache__/urls.cpython-312.pyc
  newsaggregator/newsaggregator/settings.py
  newsaggregator/newsaggregator/urls.py
  newsaggregator/requirements.txt
  newsaggregator/static/assets/css/components/about.css
  newsaggregator/static/assets/css/components/news.css
  newsaggregator/templates/components/footer.html
  newsaggregator/templates/components/navbar.html
  newsaggregator/templates/components/news.html
  newsaggregator/templates/core/about.html
  newsaggregator/templates/core/contact.html
  newsaggregator/templates/core/home.html
  newsaggregator/templates/core/index.html
  newsaggregator/templates/partials/base.html
  newsaggregator/templates/userauths/sign-in.html
  newsaggregator/templates/userauths/sign-up.html
  newsaggregator/userauths/__pycache__/__init__.cpython-312.pyc
  newsaggregator/userauths/__pycache__/admin.cpython-312.pyc
  newsaggregator/userauths/__pycache__/apps.cpython-312.pyc
  newsaggregator/userauths/__pycache__/forms.cpython-312.pyc
  newsaggregator/userauths/__pycache__/models.cpython-312.pyc
  newsaggregator/userauths/__pycache__/urls.cpython-312.pyc
  newsaggregator/userauths/__pycache__/views.cpython-312.pyc
  newsaggregator/userauths/migrations/__pycache__/0001_initial.cpython-312.pyc
  newsaggregator/userauths/migrations/__pycache__/__init__.cpython-312.pyc
  newsaggregator/userauths/views.py
Labels: GSSOC'24(Level-2)

#35 Added CONTRIBUTING.md
  CONTRIBUTING.md
Labels: GSSOC'24(Level-2)

#39 UI for website
  newsaggregator/static/assets/css/components/about.css
  newsaggregator/static/assets/css/style.css
  newsaggregator/templates/components/footer.html
  newsaggregator/templates/core/about.html
  newsaggregator/templates/partials/base.html
Labels: GSSOC'24(Level-3)

#40 alerts using toaster js and contact form backend and improved model ui
  newsaggregator/core/__pycache__/views.cpython-312.pyc
  newsaggregator/core/views.py
  newsaggregator/newsaggregator/__pycache__/settings.cpython-312.pyc
  newsaggregator/newsaggregator/settings.py
  newsaggregator/static/assets/css/components/news.css
  newsaggregator/templates/components/email.html
  newsaggregator/templates/components/news.html
  newsaggregator/templates/core/contact.html
  newsaggregator/templates/core/index.html
  newsaggregator/templates/partials/base.html
Labels: GSSOC'24(Level-3)

#41 Create greetings.yaml
  .github/workflows/greetings.yaml
Labels: GSSOC'24(Level-1)

#44 Added detailed Greeting messages using github actions.
  .github/workflows/greetings.yaml
Labels: GSSOC'24(Level-2)

#45 added CODE OF CONDUCT
  CODE_OF_CONDUCT.md
Labels: GSSOC'24(Level-1)

#50 updated landing page with cool ui
  newsaggregator/core/__pycache__/views.cpython-312.pyc
  newsaggregator/core/views.py
  newsaggregator/db.sqlite3
  newsaggregator/newsaggregator/__pycache__/settings.cpython-312.pyc
  newsaggregator/static/assets/css/userauth.css
  newsaggregator/static/assets/images/sign-in-animate.svg
  newsaggregator/static/assets/images/sign-up-animate.svg
  newsaggregator/templates/components/navbar.html
  newsaggregator/templates/partials/base.html
  newsaggregator/templates/partials/base_auth.html
  newsaggregator/templates/userauths/sign-in.html
  newsaggregator/templates/userauths/sign-up.html
Labels: gssoc, level3

#51 Create LICENSE
  LICENSE
Labels: gssoc, level2

#52 Create SECURITY.md
  SECURITY.md
Labels: gssoc, level2

#55 Added pull_request_template.md
  .github/pull_request_template.md
Labels: gssoc, level1

#53 added password and username instruction, added error messages
  newsaggregator/static/assets/css/userauth.css
  newsaggregator/templates/userauths/sign-up.html
  newsaggregator/userauths/forms.py
Labels: gssoc, level2

#56 added swiperjs carousal
  newsaggregator/core/__pycache__/admin.cpython-312.pyc
  newsaggregator/core/__pycache__/views.cpython-312.pyc
  newsaggregator/core/admin.py
  newsaggregator/core/views.py
  newsaggregator/db.sqlite3
  newsaggregator/templates/components/news.html
  newsaggregator/templates/components/swiperjs.html
  newsaggregator/userauths/__pycache__/forms.cpython-312.pyc
Labels: gssoc, level3

#59 Added option to bookmark an article and separate Bookmarked articles page
  newsaggregator/core/views.py
  newsaggregator/db.sqlite3
  newsaggregator/news/models.py
  newsaggregator/news/urls.py
  newsaggregator/news/views.py
  newsaggregator/newsaggregator/urls.py
  newsaggregator/templates/components/navbar.html
  newsaggregator/templates/components/news.html
Labels: gssoc, level2

#89 Added option for star rating
  newsaggregator/core/models.py
  newsaggregator/core/urls.py
  newsaggregator/core/views.py
  newsaggregator/db.sqlite3
  newsaggregator/static/assets/css/index.css
  newsaggregator/static/assets/js/script.js
  newsaggregator/templates/components/category-btn.html
  newsaggregator/templates/components/news.html
Labels: gssoc, level2
