Repository SiddharthBahuguna/NEWS-AGGREGATOR-PROJECT, pull requests merged in 2024-06, with the labels that each got.

#107 Feat. Added a display message in sign in page
  newsaggregator/core/__pycache__/admin.cpython-312.pyc
  newsaggregator/core/__pycache__/models.cpython-312.pyc
  newsaggregator/core/__pycache__/urls.cpython-312.pyc
  newsaggregator/core/__pycache__/views.cpython-312.pyc
  newsaggregator/core/migrations/0003_headline_average_rating_headline_rating_count_and_more.py
  newsaggregator/core/migrations/__pycache__/0002_contact.cpython-312.pyc
  newsaggregator/core/migrations/__pycache__/0003_headline_average_rating_headline_rating_count_and_more.cpython-312.pyc
  newsaggregator/core/models.py
  newsaggregator/core/views.py
  newsaggregator/db.sqlite3
  newsaggregator/newsaggregator/__pycache__/settings.cpython-312.pyc
  newsaggregator/newsaggregator/__pycache__/urls.cpython-312.pyc
  newsaggregator/templates/components/swiperjs.html
  newsaggregator/templates/userauths/sign-in.html
  newsaggregator/userauths/__pycache__/views.cpython-312.pyc
  newsaggregator/userauths/views.py
Labels: gssoc, level2

#110 navbar fixed at top
  newsaggregator/core/__pycache__/__init__.cpython-312.pyc
  newsaggregator/core/__pycache__/admin.cpython-312.pyc
  newsaggregator/core/__pycache__/apps.cpython-312.pyc
  newsaggregator/core/__pycache__/forms.cpython-312.pyc
  newsaggregator/core/__pycache__/models.cpython-312.pyc
  newsaggregator/core/__pycache__/urls.cpython-312.pyc
  newsaggregator/core/__pycache__/views.cpython-312.pyc
  newsaggregator/core/migrations/__pycache__/0001_initial.cpython-312.pyc
  newsaggregator/core/migrations/__pycache__/0002_contact.cpython-312.pyc
  newsaggregator/core/migrations/__pycache__/0003_headline_average_rating_headline_rating_count_and_more.cpython-312.pyc
  newsaggregator/core/migrations/__pycache__/__init__.cpython-312.pyc
  newsaggregator/db.sqlite3
  newsaggregator/newsaggregator/__pycache__/__init__.cpython-311.pyc
  newsaggregator/newsaggregator/__pycache__/__init__.cpython-312.pyc
  newsaggregator/newsaggregator/__pycache__/settings.cpython-312.pyc
  newsaggregator/newsaggregator/__pycache__/urls.cpython-312.pyc
  newsaggregator/newsaggregator/__pycache__/wsgi.cpython-312.pyc
  newsaggregator/static/assets/css/style.css
  newsaggregator/templates/core/about.html
  newsaggregator/templates/core/bookmarks.html
  newsaggregator/templates/core/contact.html
  newsaggregator/userauths/__pycache__/__init__.cpython-312.pyc
  newsaggregator/userauths/__pycache__/admin.cpython-312.pyc
  newsaggregator/userauths/__pycache__/apps.cpython-312.pyc
  newsaggregator/userauths/__pycache__/forms.cpython-312.pyc
  newsaggregator/userauths/__pycache__/models.cpython-312.pyc
  newsaggregator/userauths/__pycache__/urls.cpython-312.pyc
  newsaggregator/userauths/__pycache__/views.cpython-312.pyc
  newsaggregator/userauths/migrations/__pycache__/0001_initial.cpython-312.pyc
  newsaggregator/userauths/migrations/__pycache__/0002_remove_user_verified_delete_userprofile.cpython-312.pyc
  newsaggregator/userauths/migrations/__pycache__/0003_user_bio.cpython-312.pyc
  newsaggregator/userauths/migrations/__pycache__/0004_userprofile.cpython-312.pyc
  newsaggregator/userauths/migrations/__pycache__/0005_alter_userprofile_state_region.cpython-312.pyc
  newsaggregator/userauths/migrations/__pycache__/0006_alter_userprofile_profile_image.cpython-312.pyc
  newsaggregator/userauths/migrations/__pycache__/0006_alter_userprofile_profile_image_and_more.cpython-312.pyc
  newsaggregator/userauths/migrations/__pycache__/0007_alter_userprofile_profile_image.cpython-312.pyc
  newsaggregator/userauths/migrations/__pycache__/0007_delete_userprofile.cpython-312.pyc
  newsaggregator/userauths/migrations/__pycache__/0008_alter_userprofile_profile_image.cpython-312.pyc
  newsaggregator/userauths/migrations/__pycache__/__init__.cpython-312.pyc
Labels: gssoc, level2

#111 [BUG]: Fixed my bookmark page which was unable to load
  newsaggregator/core/__pycache__/urls.cpython-312.pyc
  newsaggregator/core/__pycache__/views.cpython-312.pyc
  newsaggregator/core/urls.py
  newsaggregator/core/views.py
  newsaggregator/db.sqlite3
  newsaggregator/templates/components/navbar.html
  newsaggregator/templates/core/bookmarks.html
  newsaggregator/templates/core/index.html
Labels: gssoc, level3

#113 Preloader added
  newsaggregator/static/assets/css/preloader.css
  newsaggregator/static/assets/js/preloader.js
  newsaggregator/templates/partials/base.html
Labels: gssoc, level3

#118 Chatbot feature added #80
  newsaggregator/core/__pycache__/__init__.cpython-312.pyc
  newsaggregator/core/__pycache__/admin.cpython-312.pyc
  newsaggregator/core/__pycache__/apps.cpython-312.pyc
  newsaggregator/core/__pycache__/models.cpython-312.pyc
  newsaggregator/core/__pycache__/urls.cpython-312.pyc
  newsaggregator/core/__pycache__/views.cpython-312.pyc
  newsaggregator/core/migrations/__pycache__/0001_initial.cpython-312.pyc
  newsaggregator/core/migrations/__pycache__/0002_contact.cpython-312.pyc
  newsaggregator/core/migrations/__pycache__/0003_headline_average_rating_headline_rating_count_and_more.cpython-312.pyc
  newsaggregator/core/migrations/__pycache__/__init__.cpython-312.pyc
  newsaggregator/db.sqlite3
  newsaggregator/newsaggregator/__pycache__/__init__.cpython-312.pyc
  newsaggregator/newsaggregator/__pycache__/settings.cpython-312.pyc
  newsaggregator/newsaggregator/__pycache__/urls.cpython-312.pyc
  newsaggregator/newsaggregator/__pycache__/wsgi.cpython-312.pyc
  newsaggregator/templates/partials/base.html
  newsaggregator/userauths/__pycache__/__init__.cpython-312.pyc
  newsaggregator/userauths/__pycache__/admin.cpython-312.pyc
  newsaggregator/userauths/__pycache__/apps.cpython-312.pyc
  newsaggregator/userauths/__pycache__/forms.cpython-312.pyc
  newsaggregator/userauths/__pycache__/models.cpython-312.pyc
  newsaggregator/userauths/__pycache__/urls.cpython-312.pyc
  newsaggregator/userauths/__pycache__/views.cpython-312.pyc
  newsaggregator/userauths/migrations/__pycache__/0001_initial.cpython-312.pyc
  newsaggregator/userauths/migrations/__pycache__/__init__.cpython-312.pyc
Labels: gssoc, level3

#126 google translate element added
  newsaggregator/static/assets/css/style.css
  newsaggregator/templates/components/footer.html
Labels: gssoc, level2

#128 The homepage bugs have been resolved
  newsaggregator/core/__pycache__/__init__.cpython-312.pyc
  newsaggregator/core/__pycache__/admin.cpython-312.pyc
  newsaggregator/core/__pycache__/apps.cpython-312.pyc
  newsaggregator/core/__pycache__/models.cpython-312.pyc
  newsaggregator/core/migrations/__pycache__/0001_initial.cpython-312.pyc
  newsaggregator/core/migrations/__pycache__/0002_contact.cpython-312.pyc
  newsaggregator/core/migrations/__pycache__/0003_headline_average_rating_headline_rating_count_and_more.cpython-312.pyc
  newsaggregator/core/migrations/__pycache__/__init__.cpython-312.pyc
  newsaggregator/db.sqlite3
  newsaggregator/newsaggregator/__pycache__/__init__.cpython-312.pyc
  newsaggregator/newsaggregator/__pycache__/settings.cpython-312.pyc
  newsaggregator/newsaggregator/__pycache__/urls.cpython-312.pyc
  newsaggregator/newsaggregator/__pycache__/wsgi.cpython-312.pyc
  newsaggregator/templates/components/news.html
  newsaggregator/templates/core/index.html
  newsaggregator/userauths/__pycache__/__init__.cpython-312.pyc
  newsaggregator/userauths/__pycache__/admin.cpython-312.pyc
  newsaggregator/userauths/__pycache__/apps.cpython-312.pyc
  newsaggregator/userauths/__pycache__/forms.cpython-312.pyc
  newsaggregator/userauths/__pycache__/models.cpython-312.pyc
  newsaggregator/userauths/__pycache__/urls.cpython-312.pyc
  newsaggregator/userauths/__pycache__/views.cpython-312.pyc
  newsaggregator/userauths/migrations/__pycache__/0001_initial.cpython-312.pyc
  newsaggregator/userauths/migrations/__pycache__/__init__.cpython-312.pyc
Labels: gssoc, level2

#131 News displayed on home page
  newsaggregator/core/decorators.py
  newsaggregator/core/urls.py
  newsaggregator/core/views.py
  newsaggregator/static/assets/css/base.css
  newsaggregator/static/assets/css/style.css
  newsaggregator/templates/core/about.html
  newsaggregator/templates/core/base.html
  newsaggregator/templates/core/bookmarks.html
  newsaggregator/templates/core/contact.html
  newsaggregator/templates/core/index.html
  newsaggregator/templates/userauths/sign-in.html
  newsaggregator/templates/userauths/sign-up.html
Labels: gssoc, level3

#149 improved loader updated footer improved ui
  newsaggregator/core/__pycache__/urls.cpython-312.pyc
  newsaggregator/core/__pycache__/views.cpython-312.pyc
  newsaggregator/db.sqlite3
  newsaggregator/static/assets/css/preloader.css
  newsaggregator/static/assets/css/style.css
  newsaggregator/static/assets/js/preloader.js
  newsaggregator/templates/components/footer.html
  newsaggregator/templates/partials/base.html
Labels: bug, enhancement, gssoc, level3

#150 fixed errors of news and rating and improved ui of news
  newsaggregator/core/__pycache__/urls.cpython-312.pyc
  newsaggregator/core/__pycache__/views.cpython-312.pyc
  newsaggregator/core/urls.py
  newsaggregator/core/views.py
  newsaggregator/db.sqlite3
  newsaggregator/static/assets/css/index.css
  newsaggregator/static/assets/css/preloader.css
  newsaggregator/static/assets/css/style.css
  newsaggregator/static/assets/js/preloader.js
  newsaggregator/static/assets/js/rating.js
  newsaggregator/static/assets/js/script.js
  newsaggregator/templates/components/news.html
  newsaggregator/templates/partials/base.html
Labels: bug, enhancement, gssoc, level3
